name: build_shopping_list
description: "Generates a shopping list by building a meal plan"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

#isar_version: &isar_version 3.1.8 # define the version to be used

dependencies:
  bloc: ^8.1.4
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  go_router: ^14.6.3
  i69n: ^3.0.0
  injectable: ^2.5.0
  isar: 
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  path_provider: ^2.1.5
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  isar_generator: 
    version: 3.1.8
    hosted: https://pub.isar-community.dev/

flutter:
  uses-material-design: true
